### ISSUE TITLE
Ambiguous conversion from SMARTS to SMILES

### ISSUE THREAD

**Issue by mgbaltussen** [Will-Robin/NorthNet#2]
For certain edge cases of converting reaction SMARTS to molecule SMILES, the resulting SMILES is not the same for a `NorthNet Reaction` Reactant, and the corresponding `NorthNet Compound`, that is added to the list of compounds in a network.

For some reason, enforcing canonicalization does not result in equivalent SMILES representations. This possibly has to do with the internal representation in `rdkit`, when obtaining reactant SMILES directly from a SMARTS-generated reaction.

## Code example
```python
reaction_smarts = "O=CCO.[OH-]>>OC=CO.[OH-]"

reaction_rdkit = AllChem.ReactionFromSmarts(reaction_smarts)
 
reaction_NorthNet = Reaction(reaction_rdkit)

print(f"RDKit Reaction SMILES:\t\t {Chem.MolToSmiles((reactions_rdkit[0].GetReactants()[0]), canonical=True)}")
print(f"NorthNet Reaction SMILES:\t {reaction_NorthNet.Reactants[0]}")

Mol = Compound(problem_reactant)
print(f"NorthNet Compound SMILES:\t {Mol.SMILES}")
```
>Output
```bash
RDKit Reaction SMILES:		 OCC=O
NorthNet Reaction SMILES:	 OCC=O
NorthNet Compound SMILES:	 O=CCO
```

## Proposed fix
Perform double conversion for rdkit reactants and products: 
Reactant -> Smiles -> Mol -> Smiles

instead of the current:
 Reactant -> Smiles
https://github.com/Will-Robin/NorthNet/blob/6c3d5ad1393590aa2fbf16164cd9f6d0f3da9eed/NorthNet/Classes/Reaction.py#L58-L61

**Comment by Will-Robin** [comment]
Hi Mathieu,

Good spot. 

So I think the issue here is creating the reaction using `AllChem.ReactionFromSmarts()`, which should interpret the reaction SMARTS string passed as consisting of SMARTS tokens, rather than SMILES tokens. Hence, any 'SMILES' strings in there will not be canonicalised as they are interpreted as SMARTS. Evidently, the object created in the process is the same type as can be created by other means based on reaction SMILES. It's one of the reasons I wrote the Classes module, which provides these distictions. Obviously, it's not perfect upon entry...

Upon checking the API, I found that there is a useSmiles kwarg, which may also solve this: [here](https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html#rdkit.Chem.rdChemReactions.ReactionFromSmarts).  Haven't got time to check right now.

# Some explanation

`AllChem.ReactionFromSMARTS()` is used in creating NorthNet `ReactionTemple` objects, and can be used in creating reactions:

https://github.com/Will-Robin/NorthNet/blob/main/NorthNet/Classes/ReactionTemplate.py#L56

Another way to create `RDKit AllChem.Reaction` objects from reaction SMILES strings is given in `text_parsing.conversions.py`:

https://github.com/Will-Robin/NorthNet/blob/main/NorthNet/text_parsing/conversions.py#L4

(a similar sequence is followed in `network_generation.run_reaction.py`).

# More info on RDKit Reactions

[Here is a link to The RDKit documentation on reaction handling](https://www.rdkit.org/docs/RDKit_Book.html#chemical-reaction-handling). It directs to [this specification of SMARTS](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html). Note also the grammar at the top of the section.
